---
title: "date_map homework"
author: "Owen Auston-Babcock and Bradley Collins"
date: "`r Sys.Date()`"
output: html_document
---

## Bradley's section

### Question 1

Generate sequence of dates using `lubridate`
```{r}
dates <- ymd("2015-01-01") %m+% months(seq(0, (2025 - 2015) * 6, by = 2))
```

Extract year, quarter, and ISO week number. Print the data.
```{r}
date_info <- tibble(
  DATE = dates,
  YEAR = year(dates),
  QUARTER = quarter(dates),
  ISO_WEEK = isoweek(dates)
)

date_info
```

### Question 2

Import sample
```{r}
sample_dates <- c("2018-03-15", "2020-07-20", "2023-01-10", "2025-09-05")
```

Convert sample to `lubridate` format
```{r}
sample_dates <- ymd(sample_dates)
```

Put sample into `tibble` including the differentials. Print the `tibble`.
```{r}
date_diffs <- tibble(
  DATE1 = head(sample_dates, -1),
  DATE2 = tail(sample_dates, -1),
  MONTH_DIFF = interval(DATE1, DATE2) %/% months(1),
  WEEK_DIFF = interval(DATE1, DATE2) %/% weeks(1)
)

date_diffs
```

```{r}

```
